dist: xenial
language: ruby
rvm: 2.6.2
gemfile:
  - Gemfile
sudo: false
before_install:
  - unset RAILS_ENV
  - unset RACK_ENV
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
env:
  - RAILS_VERSION=5.2.2.1
  - RAILS_VERSION=5.2.2.1 API=t
  - RAILS_VERSION=5.1.6.2
  - RAILS_VERSION=5.0.7.2
  - RAILS_VERSION=4.2.11.1
