dist: bionic
language: ruby
gemfile:
  - Gemfile
before_install:
  - unset RAILS_ENV
  - unset RACK_ENV
script: bundle exec rake test
jobs:
  allow_failures:
    - rvm: 2.7
      env: RAILS_VERSION=6.0.2.1
  include:
    - rvm: 2.6
      env: RAILS_VERSION=5.2.4.1
    - rvm: 2.6
      env: RAILS_VERSION=5.2.4.1 API=t
    - rvm: 2.5
      env: RAILS_VERSION=5.1.7
    - rvm: 2.4
      env: RAILS_VERSION=5.1.7
    - rvm: 2.4
      env: RAILS_VERSION=4.2.11.1
notifications:
  email:
    on_success: never
    on_failure: change
