name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 2.7
          rails: 6.0.3.2
        - ruby: 2.6
          rails: 5.2.4.3
        - ruby: 2.6
          rails: 5.2.4.3
          api: true
        - ruby: 2.5
          rails: 5.1.7
        - ruby: 2.4
          rails: 5.0.7.2
        - ruby: 2.4
          rails: 4.2.11.3
          bundler: 1
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: ${{ matrix.bundler }}
        bundler-cache: true
    - run: bundle exec rake test
      env:
        RAILS_VERSION: ${{ matrix.rails }}
        API: ${{ matrix.api }}
